//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MotorOrdenesVenta
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Navimex_Mo2Entities : DbContext
    {
        //public Navimex_Mo2Entities()
        //    : base("name=Navimex_Mo2Entities")
        //{
        //}
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TCMO_EstatusEnvio> TCMO_EstatusEnvio { get; set; }
        public virtual DbSet<TCMO_EstatusSolicitud> TCMO_EstatusSolicitud { get; set; }
        public virtual DbSet<TCMO_TipoSolicitud> TCMO_TipoSolicitud { get; set; }
        public virtual DbSet<TCMO_Trama> TCMO_Trama { get; set; }
        public virtual DbSet<TTMO_ResultadoEnvio> TTMO_ResultadoEnvio { get; set; }
        public virtual DbSet<TTMO_Solicitud> TTMO_Solicitud { get; set; }
    }
}
