//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MotorOrdenesVenta
{
    using System;
    using System.Collections.Generic;
    
    public partial class TCMO_Trama
    {
        public int CD_Trama { get; set; }
        public string TX_Tabla { get; set; }
        public string TX_Campo { get; set; }
        public Nullable<int> NU_Ancho { get; set; }
        public Nullable<bool> ES_AnchoVariable { get; set; }
        public Nullable<int> NU_AnchoVariable { get; set; }
        public Nullable<bool> ES_justificadoDerecha { get; set; }
        public Nullable<bool> ES_JustificadoIzquierda { get; set; }
        public string TX_CaracterDeRelleno { get; set; }
        public Nullable<int> NU_Secuencia { get; set; }
        public int TCMO_TipoSolicitud_IdTipoSolicitud { get; set; }
    
        public virtual TCMO_TipoSolicitud TCMO_TipoSolicitud { get; set; }
    }
}
