//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MotorOrdenesVenta
{
    using System;
    using System.Collections.Generic;
    
    public partial class TCMO_EstatusEnvio
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TCMO_EstatusEnvio()
        {
            this.TTMO_ResultadoEnvio = new HashSet<TTMO_ResultadoEnvio>();
        }
    
        public int CD_EstatusEnvio { get; set; }
        public string TX_EstatusEnvio { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TTMO_ResultadoEnvio> TTMO_ResultadoEnvio { get; set; }
    }
}
