//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MotorOrdenesVenta
{
    using System;
    using System.Collections.Generic;
    
    public partial class TCMO_TipoSolicitud
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TCMO_TipoSolicitud()
        {
            this.TCMO_Trama = new HashSet<TCMO_Trama>();
            this.TTMO_ResultadoEnvio = new HashSet<TTMO_ResultadoEnvio>();
            this.TTMO_Solicitud = new HashSet<TTMO_Solicitud>();
        }
    
        public int IdTipoSolicitud { get; set; }
        public string TX_Descripción { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TCMO_Trama> TCMO_Trama { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TTMO_ResultadoEnvio> TTMO_ResultadoEnvio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TTMO_Solicitud> TTMO_Solicitud { get; set; }
    }
}
