//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MotorOrdenesVenta
{
    using System;
    using System.Collections.Generic;
    
    public partial class TTMO_ResultadoEnvio
    {
        public int CD_ResultadoEnvio { get; set; }
        public int TTMO_Solicitud_CD_Solicitud { get; set; }
        public int TCMO_EstatusEnvio_CD_EstatusEnvio { get; set; }
        public Nullable<System.DateTime> FH_Envio { get; set; }
        public Nullable<System.DateTime> FH_Respuesta { get; set; }
        public string TX_Respuesta { get; set; }
        public string TX_Envio { get; set; }
        public int TCMO_TipoSolicitud_IdTipoSolicitud { get; set; }
    
        public virtual TCMO_EstatusEnvio TCMO_EstatusEnvio { get; set; }
        public virtual TCMO_TipoSolicitud TCMO_TipoSolicitud { get; set; }
        public virtual TTMO_Solicitud TTMO_Solicitud { get; set; }
    }
}
